data_ingestion:
  test_size: 0.25
  random_state: 42
  shuffle: true

model_trainer:
  chosen_model: "Random Forest Regression"   # 👈 choose model here

model_selection:
  model:
    Linear Regression:
      search_param_grid:
        fit_intercept:
          - true
          - false
          
    Ridge Regression:
      search_param_grid:
        alpha:
         - 0.001
         - 0.01
         - 0.1
         - 1
         - 10
         - 100
         - 1000

    Lasso Regression:
      search_param_grid:
        alpha:
          - 0.001
          - 0.01
          - 0.1
          - 1
          - 10
          - 100
          - 1000

    Random Forest Regression:
      search_param_grid:
        n_estimators:
         - 50
         - 10
        max_depth:
         - 10
         - 15
         - 5
        min_samples_split:
         - 2
         - 6
         - 10
        bootstrap:
         - true

    Gradient Boosting Regression:
      search_param_grid:
        n_estimators:
          - 50
          - 100
          - 150
          - 200
        max_depth:
          - 3
          - 5
          - 7
           
    DecisionTreeRegressor:
      search_param_grid:
        criterion: 
         - "squared_error"    
         - "friedman_mse" 
         - "absolute_error"   
        splitter: 
         - "best" 
         - "random"
        max_features: 
         - "sqrt" 
         - "log2"
        max_depth: 
         - 2
         - 4
         - 6
         - 8
         - 10
         - 12
         - 14
         - 16
        min_samples_split: 
         - 2
         - 4
         - 6
         - 8
         - 10
         - 12
         - 14
         - 16

