name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          dvc repro

      - name: Run model tests
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          python -m pytest tests/test_model.py

      - name: Run Flask app tests
        if: success()
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python -m pytest tests/test_flask_app.py

      